### ISSUE TITLE
Validation details unintuitive

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/lkod-validator#10]
The validation details for an invalid SPARQL endpoint catalog are not intuitively visible.
First, I get:
![image](https://github.com/datagov-cz/lkod-validator/assets/718827/fbb36d21-dced-464b-9237-4cf680adfc4b)
I can see details, which at that time, should be the primary action, but it is of the same importance as "run validation".

Then I see the details:
![image](https://github.com/datagov-cz/lkod-validator/assets/718827/cbe6f2dd-d1d5-4c35-b54a-b4e779df13aa)

And it is not entirely clear that to see what is actually wrong, I need to expand the arrow:
![image](https://github.com/datagov-cz/lkod-validator/assets/718827/432c507b-7fe6-4396-8240-e03002f27612)

**Comment by skodapetr** [comment]
Is this still relevant?

**Comment by jakubklimek** [comment]
No
